working_directory = "C:/Users/jesse"

[font]
size = 16.0
normal = { family = "UbuntuMono Nerd Font", style = "Regular" }
bold = { family = "UbuntuMono Nerd Font", style = "Regular" }
italic = { family = "UbuntuMono Nerd Font", style = "Regular" }
bold_italic = { family = "UbuntuMono Nerd Font", style = "Regular" }

[window]
startup_mode = "Maximized"
dynamic_padding = true
opacity = 1.0
decorations = "None"

[window.padding]
x = 4
y = 4

[colors.normal]
black   = "#21222c"
red     = "#ff5555"
green   = "#50fa7b"
yellow  = "#f1fa8c"
blue    = "#bd93f9"
magenta = "#ff79c6"
cyan    = "#8be9fd"
white   = "#f8f8f2"

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[colors.cursor]
text   = "CellBackground"
cursor = "CellForeground"
